@extends('layouts.app')

@section('content')
<main>
    <section class="hero" aria-labelledby="hero-title"><div class="container"><p class="eyebrow">{{ $status }}</p><h1 id="hero-title">{{ $name }}</h1><p class="lead"><strong>{{ $role }}</strong> · {{ $location }}<br>{{ $intro }}</p><a class="button" href="#work">View work</a></div></section>
    <section id="about" class="dark" aria-labelledby="about-title"><div class="container copy"><p class="eyebrow">01 / About</p><h2 id="about-title">Backend, end to end.</h2><p>{{ $about }}</p></div></section>
    <section id="experience" aria-labelledby="experience-title"><div class="container"><p class="eyebrow">02 / Experience</p><h2 id="experience-title">Career</h2><div class="timeline">@foreach ($experience as $item)<article><button type="button" class="timeline-item" aria-pressed="false" data-description="{{ $item['text'] }}"><span class="meta">{{ $item['period'] }} · {{ $item['company'] }}</span><span class="timeline-title">{{ $item['title'] }}</span><span class="timeline-marker" aria-hidden="true"></span></button><p class="timeline-description">{{ $item['text'] }}</p></article>@endforeach</div><p class="career-status" aria-live="polite">Select a role to explore it.</p></div></section>
    <section id="work" class="dark" aria-labelledby="work-title"><div class="container"><p class="eyebrow">03 / Work</p><h2 id="work-title">Systems in production.</h2><div class="cards">@foreach ($work as $item)<article class="card"><p class="meta">{{ $item['label'] }}</p><h3>{{ $item['title'] }}</h3><p>{{ $item['text'] }}</p><p class="stack">{{ $item['stack'] }}</p></article>@endforeach</div></div></section>
    <section id="projects" aria-labelledby="projects-title"><div class="container"><p class="eyebrow">04 / Projects</p><h2 id="projects-title">Public experiments.</h2><div class="cards">@foreach ($projects as $project)<article class="card"><p class="meta">{{ $project['evidence'] }}</p><h3><a href="{{ $project['url'] }}">{{ $project['name'] }} ↗</a></h3><p>{{ $project['text'] }}</p></article>@endforeach</div></div></section>
    <section id="skills" class="dark" aria-labelledby="skills-title"><div class="container"><p class="eyebrow">05 / Capabilities</p><h2 id="skills-title">Tools for the real world.</h2><div class="skill-list" role="list">@foreach ($skills as $skill)<button type="button" role="listitem" class="skill" aria-pressed="false" data-level="{{ $skill['level'] }}" data-description="{{ $skill['description'] }}">{{ $skill['name'] }}</button>@endforeach</div><p class="skill-status" aria-live="polite">Select a capability to explore it.</p></div></section>
    <section id="contact" aria-labelledby="contact-title"><div class="container copy"><p class="eyebrow">06 / Contact</p><h2 id="contact-title">Let’s build something reliable.</h2><p>For backend engineering, integrations, and systems that need to survive production:</p><p><a class="contact-link" href="mailto:{{ $email }}">{{ $email }}</a><br><a class="contact-link" href="{{ $github }}">github.com/0xkhdr ↗</a></p></div></section>
</main>
<footer><span>{{ $name }}</span></footer>
@endsection
